import { http, HttpResponse } from 'msw'
import type {
  DashboardSummary,
  AgentMessage,
  Alert,
  AuditLog,
  Backup,
  Configuration,
  ContainerlabInventory,
  CredentialProfile,
  Device,
  DiscoveryResult,
  ExecutionPlan,
  Gns3Status,
  HealthPoint,
  Lab,
  NetworkInterface,
  NetworkSettings,
  RouteEntry,
  Task,
  TaskStep,
  TerminalSession,
  Topology,
} from 'src/types/network'

export const devices: Device[] = [
  {
    id: 'cisco-iosv-r1',
    hostname: 'R1',
    vendor: 'cisco',
    model: 'IOSv',
    platform: 'IOS 15.6',
    managementIp: '172.22.45.249',
    status: 'online',
    cpu: 12,
    memory: 31,
    latencyMs: 8,
    lastSeen: '10 sec ago',
    lab: 'Cisco-IPsec-Lab',
    tags: ['core', 'ospf', 'wan'],
    osVersion: '15.6(2)T',
    uptime: '2 days, 4 hours',
    serial: '9E4K-R1-IOSV',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'connected',
      lastLogin: '2 min ago',
      authMethod: 'password',
      privilegeLevel: '15',
    },
  },
  {
    id: 'cisco-iosv-r2',
    hostname: 'R2',
    vendor: 'cisco',
    model: 'IOSv',
    platform: 'IOS 15.6',
    managementIp: '172.22.36.184',
    status: 'online',
    cpu: 16,
    memory: 35,
    latencyMs: 11,
    lastSeen: '18 sec ago',
    lab: 'Cisco-IPsec-Lab',
    tags: ['edge', 'ipsec'],
    osVersion: '15.6(2)T',
    uptime: '2 days, 1 hour',
    serial: '9E4K-R2-IOSV',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'connected',
      lastLogin: '4 min ago',
      authMethod: 'password',
      privilegeLevel: '15',
    },
  },
  {
    id: 'mikrotik-chr-mt-r1',
    hostname: 'MT-R1',
    vendor: 'mikrotik',
    model: 'CHR',
    platform: 'RouterOS 7.15',
    managementIp: '172.22.40.10',
    status: 'online',
    cpu: 9,
    memory: 27,
    latencyMs: 6,
    lastSeen: '7 sec ago',
    lab: 'Mixed-Routing-Lab',
    tags: ['routeros', 'nat', 'internet'],
    osVersion: '7.15.3',
    uptime: '5 days, 6 hours',
    serial: 'CHR-MT-R1',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'connected',
      lastLogin: '1 min ago',
      authMethod: 'password',
      privilegeLevel: 'full',
    },
  },
  {
    id: 'aruba-aoscx-sw1',
    hostname: 'SW1',
    vendor: 'aruba',
    model: 'AOS-CX Switch',
    platform: 'AOS-CX 10.13',
    managementIp: '172.22.40.20',
    status: 'warning',
    cpu: 24,
    memory: 56,
    latencyMs: 19,
    lastSeen: '35 sec ago',
    lab: 'Access-Switching-Lab',
    tags: ['switching', 'vlan', 'access'],
    osVersion: '10.13.1010',
    uptime: '14 hours',
    serial: 'AOSCX-SW1',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'degraded',
      lastLogin: '23 min ago',
      authMethod: 'ssh-key',
      privilegeLevel: 'manager',
    },
  },
  {
    id: 'linux-host-telemetry',
    hostname: 'Telemetry-VM',
    vendor: 'linux',
    model: 'Ubuntu Server',
    platform: 'Ubuntu 24.04',
    managementIp: '172.22.40.30',
    status: 'offline',
    cpu: 0,
    memory: 0,
    latencyMs: null,
    lastSeen: '12 min ago',
    lab: 'Monitoring-Lab',
    tags: ['collector', 'linux'],
    osVersion: '24.04 LTS',
    uptime: '-',
    serial: 'VM-TELEMETRY',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'disconnected',
      lastLogin: 'yesterday',
      authMethod: 'ssh-key',
      privilegeLevel: 'sudo',
    },
  },
  {
    id: 'static-routing-r1',
    hostname: 'R1',
    vendor: 'cisco',
    model: 'IOSv',
    platform: 'IOS 15.6',
    managementIp: '172.22.134.144:2201',
    status: 'online',
    cpu: 8,
    memory: 28,
    latencyMs: 3,
    lastSeen: 'live',
    lab: 'Static-Routing-Lab',
    tags: ['static-routing', 'lab', 'cisco'],
    osVersion: '15.6(2)T',
    uptime: '-',
    serial: 'SR-R1-IOSV',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'connected',
      lastLogin: 'just now',
      authMethod: 'password',
      privilegeLevel: '15',
    },
  },
  {
    id: 'static-routing-r2',
    hostname: 'R2',
    vendor: 'cisco',
    model: 'IOSv',
    platform: 'IOS 15.6',
    managementIp: '172.22.134.144:2202',
    status: 'online',
    cpu: 10,
    memory: 30,
    latencyMs: 4,
    lastSeen: 'live',
    lab: 'Static-Routing-Lab',
    tags: ['static-routing', 'lab', 'cisco'],
    osVersion: '15.6(2)T',
    uptime: '-',
    serial: 'SR-R2-IOSV',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'connected',
      lastLogin: 'just now',
      authMethod: 'password',
      privilegeLevel: '15',
    },
  },
  {
    id: 'static-routing-mt1',
    hostname: 'MT1',
    vendor: 'mikrotik',
    model: 'CHR',
    platform: 'RouterOS 7.22',
    managementIp: '172.22.134.144:2203',
    status: 'online',
    cpu: 5,
    memory: 22,
    latencyMs: 2,
    lastSeen: 'live',
    lab: 'Static-Routing-Lab',
    tags: ['static-routing', 'lab', 'mikrotik'],
    osVersion: '7.22.1',
    uptime: '-',
    serial: 'SR-MT1-CHR',
    deviceType: 'virtual',
    connection: {
      protocol: 'ssh',
      status: 'connected',
      lastLogin: 'just now',
      authMethod: 'password',
      privilegeLevel: 'full',
    },
  },
  {
    id: 'static-routing-pc1',
    hostname: 'PC1',
    vendor: 'linux',
    model: 'VPCS',
    platform: 'VPCS Simulator',
    managementIp: '192.168.10.10',
    status: 'online',
    cpu: 2,
    memory: 8,
    latencyMs: 1,
    lastSeen: 'live',
    lab: 'Static-Routing-Lab',
    tags: ['static-routing', 'lab', 'client'],
    osVersion: '0.8.3',
    uptime: '-',
    serial: 'SR-PC1-VPCS',
    deviceType: 'virtual',
    connection: {
      protocol: 'api',
      status: 'connected',
      lastLogin: 'just now',
      authMethod: 'password',
      privilegeLevel: 'user',
    },
  },
  {
    id: 'static-routing-pc2',
    hostname: 'PC2',
    vendor: 'linux',
    model: 'VPCS',
    platform: 'VPCS Simulator',
    managementIp: '192.168.20.10',
    status: 'online',
    cpu: 2,
    memory: 8,
    latencyMs: 1,
    lastSeen: 'live',
    lab: 'Static-Routing-Lab',
    tags: ['static-routing', 'lab', 'client'],
    osVersion: '0.8.3',
    uptime: '-',
    serial: 'SR-PC2-VPCS',
    deviceType: 'virtual',
    connection: {
      protocol: 'api',
      status: 'connected',
      lastLogin: 'just now',
      authMethod: 'password',
      privilegeLevel: 'user',
    },
  },
  {
    id: 'static-routing-pc3',
    hostname: 'PC3',
    vendor: 'linux',
    model: 'VPCS',
    platform: 'VPCS Simulator',
    managementIp: '192.168.30.10',
    status: 'online',
    cpu: 2,
    memory: 8,
    latencyMs: 1,
    lastSeen: 'live',
    lab: 'Static-Routing-Lab',
    tags: ['static-routing', 'lab', 'client'],
    osVersion: '0.8.3',
    uptime: '-',
    serial: 'SR-PC3-VPCS',
    deviceType: 'virtual',
    connection: {
      protocol: 'api',
      status: 'connected',
      lastLogin: 'just now',
      authMethod: 'password',
      privilegeLevel: 'user',
    },
  },
]

export const interfaces: NetworkInterface[] = [
  {
    id: 'r1-gi0-0',
    deviceId: 'cisco-iosv-r1',
    name: 'GigabitEthernet0/0',
    description: 'WAN',
    ipAddress: '172.22.45.249/20',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '1.8 GB',
    tx: '924 MB',
    errors: 0,
  },
  {
    id: 'r1-gi0-1',
    deviceId: 'cisco-iosv-r1',
    name: 'GigabitEthernet0/1',
    description: 'LAN transit',
    ipAddress: '10.10.12.1/30',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '884 MB',
    tx: '811 MB',
    errors: 0,
  },
  {
    id: 'sw1-gi1-0-1',
    deviceId: 'aruba-aoscx-sw1',
    name: '1/1/1',
    description: 'R1 uplink',
    ipAddress: '-',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '622 MB',
    tx: '608 MB',
    errors: 3,
  },
  {
    id: 'sr-r1-gi0-0',
    deviceId: 'static-routing-r1',
    name: 'GigabitEthernet0/0',
    description: 'PC1 segment',
    ipAddress: '192.168.10.1/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '12 MB',
    tx: '9 MB',
    errors: 0,
  },
  {
    id: 'sr-r1-gi0-1',
    deviceId: 'static-routing-r1',
    name: 'GigabitEthernet0/1',
    description: 'Link to R2',
    ipAddress: '10.10.12.1/30',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '18 MB',
    tx: '15 MB',
    errors: 0,
  },
  {
    id: 'sr-r1-gi0-2',
    deviceId: 'static-routing-r1',
    name: 'GigabitEthernet0/2',
    description: 'NAT management',
    ipAddress: '192.168.42.85/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '3 MB',
    tx: '4 MB',
    errors: 0,
  },
  {
    id: 'sr-r1-gi0-3',
    deviceId: 'static-routing-r1',
    name: 'GigabitEthernet0/3',
    description: 'Link to MT1',
    ipAddress: '10.10.13.1/30',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '8 MB',
    tx: '6 MB',
    errors: 0,
  },
  {
    id: 'sr-r2-gi0-0',
    deviceId: 'static-routing-r2',
    name: 'GigabitEthernet0/0',
    description: 'PC2 segment',
    ipAddress: '192.168.20.1/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '11 MB',
    tx: '8 MB',
    errors: 0,
  },
  {
    id: 'sr-r2-gi0-1',
    deviceId: 'static-routing-r2',
    name: 'GigabitEthernet0/1',
    description: 'Link to R1',
    ipAddress: '10.10.12.2/30',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '15 MB',
    tx: '18 MB',
    errors: 0,
  },
  {
    id: 'sr-r2-gi0-2',
    deviceId: 'static-routing-r2',
    name: 'GigabitEthernet0/2',
    description: 'NAT management',
    ipAddress: '192.168.42.136/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '2 MB',
    tx: '3 MB',
    errors: 0,
  },
  {
    id: 'sr-mt1-ether1',
    deviceId: 'static-routing-mt1',
    name: 'ether1',
    description: 'Link to R1',
    ipAddress: '10.10.13.2/30',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '6 MB',
    tx: '8 MB',
    errors: 0,
  },
  {
    id: 'sr-mt1-ether2',
    deviceId: 'static-routing-mt1',
    name: 'ether2',
    description: 'PC3 segment',
    ipAddress: '192.168.30.1/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '9 MB',
    tx: '11 MB',
    errors: 0,
  },
  {
    id: 'sr-mt1-ether4',
    deviceId: 'static-routing-mt1',
    name: 'ether4',
    description: 'NAT management',
    ipAddress: '192.168.42.52/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '1 Gbps',
    duplex: 'Full',
    rx: '1 MB',
    tx: '2 MB',
    errors: 0,
  },
  {
    id: 'sr-pc1-eth0',
    deviceId: 'static-routing-pc1',
    name: 'eth0',
    description: 'LAN to R1',
    ipAddress: '192.168.10.10/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '100 Mbps',
    duplex: 'Full',
    rx: '9 MB',
    tx: '12 MB',
    errors: 0,
  },
  {
    id: 'sr-pc2-eth0',
    deviceId: 'static-routing-pc2',
    name: 'eth0',
    description: 'LAN to R2',
    ipAddress: '192.168.20.10/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '100 Mbps',
    duplex: 'Full',
    rx: '8 MB',
    tx: '11 MB',
    errors: 0,
  },
  {
    id: 'sr-pc3-eth0',
    deviceId: 'static-routing-pc3',
    name: 'eth0',
    description: 'LAN to MT1',
    ipAddress: '192.168.30.10/24',
    adminStatus: 'up',
    operationalStatus: 'up',
    speed: '100 Mbps',
    duplex: 'Full',
    rx: '11 MB',
    tx: '9 MB',
    errors: 0,
  },
]

export const routes: RouteEntry[] = [
  {
    id: 'r1-default',
    deviceId: 'cisco-iosv-r1',
    network: '0.0.0.0',
    prefix: '/0',
    protocol: 'static',
    nextHop: '172.22.32.1',
    interface: 'GigabitEthernet0/0',
    metric: 1,
  },
  {
    id: 'r1-ospf-lan',
    deviceId: 'cisco-iosv-r1',
    network: '10.10.12.0',
    prefix: '/30',
    protocol: 'ospf',
    nextHop: 'connected',
    interface: 'GigabitEthernet0/1',
    metric: 10,
  },
  {
    id: 'mt-default',
    deviceId: 'mikrotik-chr-mt-r1',
    network: '0.0.0.0',
    prefix: '/0',
    protocol: 'static',
    nextHop: '172.22.40.1',
    interface: 'ether1',
    metric: 1,
  },
  {
    id: 'sr-r1-to-r2',
    deviceId: 'static-routing-r1',
    network: '192.168.20.0',
    prefix: '/24',
    protocol: 'static',
    nextHop: '10.10.12.2',
    interface: 'GigabitEthernet0/1',
    metric: 1,
  },
  {
    id: 'sr-r1-to-mt',
    deviceId: 'static-routing-r1',
    network: '192.168.30.0',
    prefix: '/24',
    protocol: 'static',
    nextHop: '10.10.13.2',
    interface: 'GigabitEthernet0/3',
    metric: 1,
  },
  {
    id: 'sr-r2-to-r1',
    deviceId: 'static-routing-r2',
    network: '192.168.10.0',
    prefix: '/24',
    protocol: 'static',
    nextHop: '10.10.12.1',
    interface: 'GigabitEthernet0/1',
    metric: 1,
  },
  {
    id: 'sr-r2-to-mt',
    deviceId: 'static-routing-r2',
    network: '192.168.30.0',
    prefix: '/24',
    protocol: 'static',
    nextHop: '10.10.12.1',
    interface: 'GigabitEthernet0/1',
    metric: 2,
  },
  {
    id: 'sr-mt1-to-r1',
    deviceId: 'static-routing-mt1',
    network: '192.168.10.0',
    prefix: '/24',
    protocol: 'static',
    nextHop: '10.10.13.1',
    interface: 'ether1',
    metric: 1,
  },
  {
    id: 'sr-mt1-to-r2',
    deviceId: 'static-routing-mt1',
    network: '192.168.20.0',
    prefix: '/24',
    protocol: 'static',
    nextHop: '10.10.13.1',
    interface: 'ether1',
    metric: 2,
  },
  {
    id: 'sr-mt1-to-rs-link',
    deviceId: 'static-routing-mt1',
    network: '10.10.12.0',
    prefix: '/30',
    protocol: 'static',
    nextHop: '10.10.13.1',
    interface: 'ether1',
    metric: 1,
  },
]

export const labs: Lab[] = [
  {
    id: 'cisco-ipsec-lab',
    name: 'Cisco-IPsec-Lab',
    engine: 'gns3',
    nodes: 4,
    status: 'running',
    cpu: 28,
    ram: 42,
    created: '2026-08-21',
  },
  {
    id: 'static-routing-lab',
    name: 'Static-Routing-Lab',
    engine: 'gns3',
    nodes: 4,
    status: 'running',
    cpu: 18,
    ram: 24,
    created: '2026-08-24',
  },
  {
    id: 'mixed-routing-lab',
    name: 'Mixed-Routing-Lab',
    engine: 'containerlab',
    nodes: 6,
    status: 'running',
    cpu: 36,
    ram: 51,
    created: '2026-08-22',
  },
]

export const topology: Topology = {
  id: 'a6967457-f60e-4752-be8f-6b66e925245c',
  name: 'AI Network Lab Topology',
  projectId: 'a6967457-f60e-4752-be8f-6b66e925245c',
  nodes: [
    { id: 'cisco-iosv-r1', hostname: 'R1', vendor: 'cisco', kind: 'router', nodeType: 'qemu', status: 'online', ip: '172.22.45.249' },
    { id: 'cisco-iosv-r2', hostname: 'R2', vendor: 'cisco', kind: 'router', nodeType: 'qemu', status: 'online', ip: '172.22.36.184' },
    { id: 'mikrotik-chr-mt-r1', hostname: 'MT-R1', vendor: 'mikrotik', kind: 'router', nodeType: 'qemu', status: 'online', ip: '172.22.40.10' },
    { id: 'aruba-aoscx-sw1', hostname: 'SW1', vendor: 'aruba', kind: 'switch', nodeType: 'qemu', status: 'warning', ip: '172.22.40.20' },
    { id: 'linux-host-telemetry', hostname: 'Telemetry-VM', vendor: 'linux', kind: 'host', nodeType: 'docker', status: 'offline', ip: '172.22.40.30' },
    { id: 'cloud-nat', hostname: 'NAT', vendor: 'other', kind: 'nat', nodeType: 'cloud', status: 'online', ip: 'dhcp' },
  ],
  links: [
    { id: 'r1-sw1', source: 'cisco-iosv-r1', target: 'aruba-aoscx-sw1', sourceInterface: 'Gi0/1', targetInterface: '1/1/1', status: 'up' },
    { id: 'r2-sw1', source: 'cisco-iosv-r2', target: 'aruba-aoscx-sw1', sourceInterface: 'Gi0/1', targetInterface: '1/1/2', status: 'up' },
    { id: 'mt-sw1', source: 'mikrotik-chr-mt-r1', target: 'aruba-aoscx-sw1', sourceInterface: 'ether1', targetInterface: '1/1/3', status: 'up' },
    { id: 'telemetry-sw1', source: 'linux-host-telemetry', target: 'aruba-aoscx-sw1', sourceInterface: 'ens33', targetInterface: '1/1/4', status: 'down' },
    { id: 'nat-r1', source: 'cloud-nat', target: 'cisco-iosv-r1', sourceInterface: 'nat0', targetInterface: 'Gi0/0', status: 'up' },
  ],
}

export const staticRoutingTopology: Topology = {
  id: 'static-routing-lab',
  name: 'Static Routing Lab',
  projectId: 'static-routing-lab',
  nodes: [
    { id: 'static-routing-r1', hostname: 'R1', vendor: 'cisco', kind: 'router', nodeType: 'qemu', status: 'online', ip: '172.22.134.144:2201' },
    { id: 'static-routing-r2', hostname: 'R2', vendor: 'cisco', kind: 'router', nodeType: 'qemu', status: 'online', ip: '172.22.134.144:2202' },
    { id: 'static-routing-mt1', hostname: 'MT1', vendor: 'mikrotik', kind: 'router', nodeType: 'qemu', status: 'online', ip: '172.22.134.144:2203' },
    { id: 'static-routing-pc1', hostname: 'PC1', vendor: 'linux', kind: 'host', nodeType: 'vpcs', status: 'online', ip: '192.168.10.10' },
    { id: 'static-routing-pc2', hostname: 'PC2', vendor: 'linux', kind: 'host', nodeType: 'vpcs', status: 'online', ip: '192.168.20.10' },
    { id: 'static-routing-pc3', hostname: 'PC3', vendor: 'linux', kind: 'host', nodeType: 'vpcs', status: 'online', ip: '192.168.30.10' },
  ],
  links: [
    { id: 'sr-r1-r2', source: 'static-routing-r1', target: 'static-routing-r2', sourceInterface: 'Gi0/1', targetInterface: 'Gi0/1', status: 'up' },
    { id: 'sr-pc1-r1', source: 'static-routing-pc1', target: 'static-routing-r1', sourceInterface: 'eth0', targetInterface: 'Gi0/0', status: 'up' },
    { id: 'sr-pc2-r2', source: 'static-routing-pc2', target: 'static-routing-r2', sourceInterface: 'eth0', targetInterface: 'Gi0/0', status: 'up' },
    { id: 'sr-r1-mt1', source: 'static-routing-r1', target: 'static-routing-mt1', sourceInterface: 'Gi0/3', targetInterface: 'ether1', status: 'up' },
    { id: 'sr-mt1-pc3', source: 'static-routing-mt1', target: 'static-routing-pc3', sourceInterface: 'ether2', targetInterface: 'eth0', status: 'up' },
  ],
  layout: {
    'static-routing-pc1': { x: 60, y: 300 },
    'static-routing-r1': { x: 60, y: 130 },
    'static-routing-r2': { x: 360, y: 130 },
    'static-routing-pc2': { x: 360, y: 300 },
    'static-routing-mt1': { x: 210, y: 130 },
    'static-routing-pc3': { x: 210, y: 300 },
  },
}

const AI_NETWORK_PROJECT_ID = 'a6967457-f60e-4752-be8f-6b66e925245c'
const STATIC_ROUTING_PROJECT_ID = '5845909f-e540-4011-a7f7-86112c1a539d'

const topologyByProjectId: Record<string, Topology> = {
  [AI_NETWORK_PROJECT_ID]: topology,
  [STATIC_ROUTING_PROJECT_ID]: {
    ...staticRoutingTopology,
    id: STATIC_ROUTING_PROJECT_ID,
    projectId: STATIC_ROUTING_PROJECT_ID,
    name: 'Static Routing Lab',
  },
}

export const gns3Status: Gns3Status = {
  server: 'connected',
  vm: 'connected',
  controller: 'http://localhost:3080',
  projects: [
    { id: AI_NETWORK_PROJECT_ID, name: 'AI Network Agent Lab', nodes: 6, status: 'running', created: '2026-08-21' },
    { id: STATIC_ROUTING_PROJECT_ID, name: 'Static-Routing-Lab', nodes: 6, status: 'running', created: '2026-08-24' },
    { id: 'access-switching-lab', name: 'Access-Switching-Lab', nodes: 3, status: 'degraded', created: '2026-08-23' },
  ],
}

export const containerlabInventory: ContainerlabInventory = {
  topologyFiles: [
    { name: 'ai-network-lab.clab.yml', status: 'valid', updated: '2026-08-24 14:10' },
    { name: 'mixed-routing.clab.yml', status: 'valid', updated: '2026-08-23 22:45' },
  ],
  runningLabs: labs.filter((lab) => lab.engine === 'containerlab'),
  nodes: [
    { name: 'r1', kind: 'vr-cisco', image: 'vrnetlab/cisco_iol:latest', status: 'running' },
    { name: 'mt1', kind: 'vr-mikrotik', image: 'vrnetlab/mikrotik_routeros:7.15', status: 'running' },
    { name: 'sw1', kind: 'linux', image: 'ghcr.io/srl-labs/network-multitool', status: 'running' },
  ],
  images: [
    { name: 'vrnetlab/cisco_iol:latest', size: '1.8 GB', source: 'local' },
    { name: 'vrnetlab/mikrotik_routeros:7.15', size: '412 MB', source: 'local' },
    { name: 'ghcr.io/srl-labs/network-multitool', size: '92 MB', source: 'registry' },
  ],
  yaml: `name: ai-network-lab

topology:
  nodes:
    r1:
      kind: vr-cisco
    mt1:
      kind: vr-mikrotik
    sw1:
      kind: linux`,
}

export const agentMessages: AgentMessage[] = [
  {
    id: 'msg-system-1',
    role: 'system',
    content: 'Agent is configured to require approval before network changes and to perform automatic backups before deployment.',
    createdAt: '14:18:01',
  },
  {
    id: 'msg-user-1',
    role: 'user',
    content: 'Configure OSPF between R1 and R2',
    createdAt: '14:18:20',
  },
  {
    id: 'msg-agent-1',
    role: 'assistant',
    content: 'I prepared a non-destructive plan. No configuration will be pushed until approval is granted.',
    createdAt: '14:18:24',
  },
]

export const executionPlan: ExecutionPlan = {
  id: 'plan-ospf-r1-r2',
  task: 'Configure OSPF between R1 and R2',
  devices: ['R1', 'R2'],
  plannedActions: [
    'Check interface status',
    'Check existing routing',
    'Generate OSPF configuration',
    'Validate management connectivity',
    'Backup running configuration',
    'Apply configuration',
    'Verify neighbor state',
    'Test routes',
    'Save configuration',
  ],
  risk: 'low',
  requiresApproval: true,
}

export const tasks: Task[] = [
  {
    id: 'task-ospf-r1-r2',
    name: 'Configure OSPF',
    device: 'R1, R2',
    action: 'Configuration',
    status: 'success',
    started: '14:20',
    duration: '18 sec',
    user: 'admin',
    agent: 'AI Agent',
  },
  {
    id: 'task-backup-all',
    name: 'Backup all configs',
    device: 'All devices',
    action: 'Backup',
    status: 'running',
    started: '14:31',
    duration: '42 sec',
    user: 'admin',
    agent: 'Scheduler',
  },
  {
    id: 'task-check-mt',
    name: 'Check MikroTik internet reachability',
    device: 'MT-R1',
    action: 'Validation',
    status: 'failed',
    started: '13:52',
    duration: '11 sec',
    user: 'admin',
    agent: 'AI Agent',
  },
]

export const taskSteps: TaskStep[] = [
  {
    id: 'step-plan',
    taskId: 'task-ospf-r1-r2',
    name: 'Planning',
    status: 'success',
    timestamp: '14:20:01',
    output: 'Intent parsed and device set resolved to R1, R2.',
  },
  {
    id: 'step-precheck',
    taskId: 'task-ospf-r1-r2',
    name: 'Pre-check',
    status: 'success',
    timestamp: '14:20:04',
    output: 'SSH reachable, privilege 15 confirmed, interfaces are up.',
  },
  {
    id: 'step-backup',
    taskId: 'task-ospf-r1-r2',
    name: 'Backup',
    status: 'success',
    timestamp: '14:20:08',
    output: 'Running configuration backed up for both devices.',
  },
  {
    id: 'step-config',
    taskId: 'task-ospf-r1-r2',
    name: 'Configuration',
    status: 'success',
    timestamp: '14:20:12',
    output: 'OSPF process and network statements applied.',
  },
  {
    id: 'step-validation',
    taskId: 'task-ospf-r1-r2',
    name: 'Validation',
    status: 'success',
    timestamp: '14:20:17',
    output: 'Neighbor state FULL, expected routes installed.',
  },
  {
    id: 'step-save',
    taskId: 'task-ospf-r1-r2',
    name: 'Save',
    status: 'success',
    timestamp: '14:20:18',
    output: 'Configuration saved.',
  },
]

export const terminalSession: TerminalSession = {
  id: 'terminal-r1',
  deviceId: 'cisco-iosv-r1',
  prompt: 'R1#',
  protocol: 'ssh',
  host: '172.22.45.249',
  status: 'connected',
  history: ['show ip interface brief', 'show ip route', 'show ip ospf neighbor'],
  output: [
    'Connecting to 172.22.45.249 via SSH...',
    'SSH connected. Privilege level 15.',
    'R1# show ip interface brief',
    'Interface              IP-Address      OK? Method Status                Protocol',
    'GigabitEthernet0/0     172.22.45.249   YES manual up                    up',
    'GigabitEthernet0/1     10.10.12.1      YES manual up                    up',
    'Loopback0              1.1.1.1         YES manual up                    up',
    'R1#',
  ],
}

export const configurations: Configuration[] = [
  {
    id: 'cfg-r1-gi0-1',
    deviceId: 'cisco-iosv-r1',
    mode: 'structured',
    candidate: 'Interface GigabitEthernet0/1 / IP 192.168.10.1/24 / Admin State Enabled',
    generated: `interface GigabitEthernet0/1
 description LAN user segment
 ip address 192.168.10.1 255.255.255.0
 no shutdown`,
    risk: 'low',
    validation: [
      { check: 'Management connectivity', result: 'safe', detail: 'Management path stays on Gi0/0.' },
      { check: 'Routing impact', result: 'safe', detail: 'No default route or OSPF process changes.' },
      { check: 'Potential lockout', result: 'safe', detail: 'No AAA, SSH, ACL, or mgmt VRF change detected.' },
    ],
  },
]

export const backups: Backup[] = [
  { id: 'backup-r1-001', deviceId: 'cisco-iosv-r1', device: 'R1', backupTime: '2026-08-24 14:20:08', type: 'running', size: '18 KB', createdBy: 'AI Agent' },
  { id: 'backup-r2-001', deviceId: 'cisco-iosv-r2', device: 'R2', backupTime: '2026-08-24 14:20:08', type: 'running', size: '17 KB', createdBy: 'AI Agent' },
  { id: 'backup-mt-001', deviceId: 'mikrotik-chr-mt-r1', device: 'MT-R1', backupTime: '2026-08-24 13:50:44', type: 'running', size: '9 KB', createdBy: 'admin' },
]

export const alerts: Alert[] = [
  { id: 'alert-sw1-errors', type: 'Interface Down', severity: 'medium', device: 'SW1', message: 'Interface 1/1/4 is down toward Telemetry-VM.', createdAt: '14:34:11', status: 'open' },
  { id: 'alert-mt-routing', type: 'Routing Neighbor Down', severity: 'high', device: 'MT-R1', message: 'OSPF adjacency to R1 not established.', createdAt: '13:52:09', status: 'acknowledged' },
  { id: 'alert-linux-offline', type: 'Device Offline', severity: 'critical', device: 'Telemetry-VM', message: 'Host has not responded for 12 minutes.', createdAt: '14:25:30', status: 'open' },
]

export const auditLogs: AuditLog[] = [
  { id: 'audit-plan', time: '14:18:24', user: 'admin', action: 'AI generated config', device: 'R1, R2', result: 'success', source: 'ai-agent', details: 'OSPF plan generated and marked low risk.' },
  { id: 'audit-approval', time: '14:19:10', user: 'admin', action: 'User approved config', device: 'R1, R2', result: 'success', source: 'user', details: 'Approval recorded before push.' },
  { id: 'audit-ssh', time: '14:20:02', user: 'system', action: 'SSH login', device: 'R1', result: 'success', source: 'automation', details: 'Privilege level 15 confirmed.' },
  { id: 'audit-backup', time: '14:20:08', user: 'system', action: 'Backup created', device: 'R1, R2', result: 'success', source: 'automation', details: 'Running configurations archived.' },
  { id: 'audit-push', time: '14:20:12', user: 'system', action: 'Config pushed', device: 'R1, R2', result: 'success', source: 'automation', details: 'OSPF configuration applied.' },
]

export const credentialProfiles: CredentialProfile[] = [
  { id: 'cred-cisco-lab', name: 'Cisco Lab', vendor: 'cisco', username: 'admin', authType: 'password', secretPreview: '••••••••', lastTest: '5 min ago', status: 'valid' },
  { id: 'cred-mikrotik-lab', name: 'MikroTik Lab', vendor: 'mikrotik', username: 'admin', authType: 'password', secretPreview: '••••••••', lastTest: '18 min ago', status: 'valid' },
  { id: 'cred-aruba-lab', name: 'Aruba Lab', vendor: 'aruba', username: 'admin', authType: 'ssh-key', secretPreview: '••••••••', lastTest: '23 min ago', status: 'failed' },
]

export const discoveryResults: DiscoveryResult[] = [
  { id: 'disc-r1', ip: '172.22.45.249', hostname: 'R1', vendor: 'cisco', platform: 'IOSv', ssh: 'open', snmp: 'closed', status: 'ready' },
  { id: 'disc-r2', ip: '172.22.36.184', hostname: 'R2', vendor: 'cisco', platform: 'IOSv', ssh: 'open', snmp: 'closed', status: 'ready' },
  { id: 'disc-mt1', ip: '172.22.40.10', hostname: 'MT-R1', vendor: 'mikrotik', platform: 'RouterOS CHR', ssh: 'open', snmp: 'unknown', status: 'added' },
  { id: 'disc-sw1', ip: '172.22.40.20', hostname: 'SW1', vendor: 'aruba', platform: 'AOS-CX', ssh: 'open', snmp: 'open', status: 'ready' },
]

export const networkSettings: NetworkSettings = {
  general: {
    workspaceName: 'AI Network Agent Lab',
    timezone: 'Asia/Makassar',
    defaultView: 'dashboard',
  },
  ai: {
    provider: 'OpenAI',
    model: 'gpt-5',
    temperature: 0.2,
    maximumTokens: 4096,
    requireApproval: true,
    automaticBackup: true,
    postChangeValidation: true,
    automaticRollback: true,
    allowDestructiveCommands: false,
  },
  ssh: {
    timeoutSeconds: 10,
    commandTimeoutSeconds: 30,
    strictHostKeyChecking: true,
  },
}

export const healthSeries: Record<string, HealthPoint[]> = {
  '1H': [
    { time: '00:00', online: 38, offline: 4, latency: 9, packetLoss: 0.1, configFailures: 0 },
    { time: '00:15', online: 39, offline: 3, latency: 11, packetLoss: 0.2, configFailures: 1 },
    { time: '00:30', online: 39, offline: 3, latency: 8, packetLoss: 0.1, configFailures: 0 },
    { time: '00:45', online: 40, offline: 2, latency: 7, packetLoss: 0.1, configFailures: 0 },
  ],
  '6H': [
    { time: '18:00', online: 37, offline: 5, latency: 13, packetLoss: 0.4, configFailures: 1 },
    { time: '20:00', online: 38, offline: 4, latency: 10, packetLoss: 0.2, configFailures: 0 },
    { time: '22:00', online: 40, offline: 2, latency: 8, packetLoss: 0.1, configFailures: 0 },
    { time: '00:00', online: 40, offline: 2, latency: 7, packetLoss: 0.1, configFailures: 0 },
  ],
  '24H': [
    { time: 'Mon', online: 36, offline: 6, latency: 14, packetLoss: 0.6, configFailures: 2 },
    { time: 'Tue', online: 38, offline: 4, latency: 12, packetLoss: 0.4, configFailures: 1 },
    { time: 'Wed', online: 39, offline: 3, latency: 9, packetLoss: 0.2, configFailures: 1 },
    { time: 'Thu', online: 40, offline: 2, latency: 8, packetLoss: 0.1, configFailures: 0 },
  ],
  '7D': [
    { time: 'D-6', online: 34, offline: 8, latency: 18, packetLoss: 0.9, configFailures: 3 },
    { time: 'D-4', online: 37, offline: 5, latency: 14, packetLoss: 0.4, configFailures: 2 },
    { time: 'D-2', online: 39, offline: 3, latency: 10, packetLoss: 0.2, configFailures: 1 },
    { time: 'Now', online: 40, offline: 2, latency: 8, packetLoss: 0.1, configFailures: 0 },
  ],
  '30D': [
    { time: 'W1', online: 31, offline: 11, latency: 22, packetLoss: 1.2, configFailures: 4 },
    { time: 'W2', online: 35, offline: 7, latency: 16, packetLoss: 0.6, configFailures: 2 },
    { time: 'W3', online: 38, offline: 4, latency: 11, packetLoss: 0.3, configFailures: 1 },
    { time: 'W4', online: 40, offline: 2, latency: 8, packetLoss: 0.1, configFailures: 0 },
  ],
}

export const summary: DashboardSummary = {
  totalDevices: {
    total: 42,
    online: 30,
    offline: 8,
    warning: 4,
  },
  activeLabs: {
    total: 6,
    gns3: 2,
    containerlab: 4,
  },
  aiOperations: {
    totalToday: 18,
    success: 14,
    running: 2,
    failed: 2,
  },
  networkHealth: {
    score: 96,
    label: 'Healthy',
  },
}

export const NetworkHandlers = [
  http.get('/api/network/dashboard', () => HttpResponse.json({ status: 200, data: summary })),
  http.get('/api/network/health', ({ request }) => {
    const range = new URL(request.url).searchParams.get('range') ?? '24H'
    return HttpResponse.json({ status: 200, data: healthSeries[range] ?? healthSeries['24H'] })
  }),
  http.get('/api/network/devices', () => HttpResponse.json({ status: 200, data: devices })),
  http.get('/api/network/devices/:id', ({ params }) => {
    const device = devices.find((item) => item.id === params.id)
    if (!device) {
      return HttpResponse.json({ status: 404, msg: 'Device not found' }, { status: 404 })
    }

    return HttpResponse.json({
      status: 200,
      data: {
        device,
        interfaces: interfaces.filter((item) => item.deviceId === device.id),
        routes: routes.filter((item) => item.deviceId === device.id),
      },
    })
  }),
  http.get('/api/network/labs', () => HttpResponse.json({ status: 200, data: labs })),
  http.get('/api/network/labs/:id', ({ params }) => {
    const lab = labs.find((item) => item.id === params.id)
    if (!lab) {
      return HttpResponse.json({ status: 404, msg: 'Lab not found' }, { status: 404 })
    }
    const projectTopology =
      lab.id === STATIC_ROUTING_PROJECT_ID
        ? topologyByProjectId[STATIC_ROUTING_PROJECT_ID]
        : lab.id === AI_NETWORK_PROJECT_ID
          ? topologyByProjectId[AI_NETWORK_PROJECT_ID]
          : topology
    return HttpResponse.json({ status: 200, data: { lab, topology: projectTopology } })
  }),
  http.get('/api/network/topology', ({ request }) => {
    const projectId = new URL(request.url).searchParams.get('project_id')
    if (projectId && topologyByProjectId[projectId]) {
      return HttpResponse.json({ status: 200, data: topologyByProjectId[projectId] })
    }
    return HttpResponse.json({ status: 200, data: topology })
  }),
  http.get('/api/network/gns3', () => HttpResponse.json({ status: 200, data: gns3Status })),
  http.get('/api/network/containerlab', () => HttpResponse.json({ status: 200, data: containerlabInventory })),
  http.get('/api/network/configurations', () => HttpResponse.json({ status: 200, data: configurations })),
  http.get('/api/network/backups', () => HttpResponse.json({ status: 200, data: backups })),
  http.get('/api/network/alerts', () => HttpResponse.json({ status: 200, data: alerts })),
  http.get('/api/network/audit', () => HttpResponse.json({ status: 200, data: auditLogs })),
  http.get('/api/network/credentials', () => HttpResponse.json({ status: 200, data: credentialProfiles })),
  http.get('/api/network/discovery', () => HttpResponse.json({ status: 200, data: discoveryResults })),
  http.get('/api/network/settings', () => HttpResponse.json({ status: 200, data: networkSettings })),
  http.get('/api/network/agent/messages', () => HttpResponse.json({ status: 200, data: agentMessages })),
  http.get('/api/network/agent/plan', () => HttpResponse.json({ status: 200, data: executionPlan })),
  http.post('/api/network/agent/plan', async ({ request }) => {
    const body = (await request.json()) as { task?: string; devices?: string[] }
    return HttpResponse.json({
      status: 200,
      data: {
        ...executionPlan,
        task: body.task || executionPlan.task,
        devices: body.devices?.length ? body.devices : executionPlan.devices,
      },
    })
  }),
  http.get('/api/network/tasks', () => HttpResponse.json({ status: 200, data: tasks })),
  http.get('/api/network/tasks/:id', ({ params }) => {
    const task = tasks.find((item) => item.id === params.id)
    if (!task) {
      return HttpResponse.json({ status: 404, msg: 'Task not found' }, { status: 404 })
    }

    return HttpResponse.json({
      status: 200,
      data: {
        task,
        steps: taskSteps.filter((step) => step.taskId === task.id),
      },
    })
  }),
  http.get('/api/network/terminal/session', () => HttpResponse.json({ status: 200, data: terminalSession })),
]
