from fastapi import APIRouter
from app.api.v1.endpoints import devices, config, monitoring, topology, audit, mikrotik, cisco, aruba, asa, ruijie, fortigate, gns3, policy, terminal, tasks, alerts, backups, agent, credentials, settings, discovery, containerlab, ninerouter, agent_sessions

api_router = APIRouter()
api_router.include_router(devices.router, prefix="/devices", tags=["devices"])
api_router.include_router(config.router, prefix="/config", tags=["config"])
api_router.include_router(monitoring.router, prefix="/monitoring", tags=["monitoring"])
api_router.include_router(topology.router, prefix="/topology", tags=["topology"])
api_router.include_router(audit.router, prefix="/audit", tags=["audit"])
api_router.include_router(mikrotik.router, prefix="/mikrotik", tags=["mikrotik"])
api_router.include_router(cisco.router, prefix="/cisco", tags=["cisco"])
api_router.include_router(aruba.router, prefix="/aruba", tags=["aruba"])
api_router.include_router(asa.router, prefix="/asa", tags=["asa"])
api_router.include_router(ruijie.router, prefix="/ruijie", tags=["ruijie"])
api_router.include_router(fortigate.router, prefix="/fortigate", tags=["fortigate"])
api_router.include_router(gns3.router, prefix="/gns3", tags=["gns3"])
api_router.include_router(policy.router, prefix="/policy", tags=["policy"])
api_router.include_router(terminal.router, prefix="/terminal", tags=["terminal"])
api_router.include_router(tasks.router, prefix="/tasks", tags=["tasks"])
api_router.include_router(alerts.router, prefix="/alerts", tags=["alerts"])
api_router.include_router(backups.router, prefix="/backups", tags=["backups"])
api_router.include_router(agent.router, prefix="/agent", tags=["agent"])
api_router.include_router(agent_sessions.router, prefix="/agent", tags=["agent"])
api_router.include_router(credentials.router, prefix="/credentials", tags=["credentials"])
api_router.include_router(settings.router, prefix="/settings", tags=["settings"])
api_router.include_router(discovery.router, prefix="/discovery", tags=["discovery"])
api_router.include_router(containerlab.router, prefix="/containerlab", tags=["containerlab"])
api_router.include_router(ninerouter.router, prefix="/ninerouter", tags=["ninerouter"])
